

loader_params: 

    'train_bs': 4
    'val_bs': 8
    'csv_root': 'meta_files/meta_data_infer_val_copy.csv'
    # 'csv_root': 'meta_files/meta_data_test.csv'
    'scale_dose_dict': 'meta_files/PTV_DICT.json'
    'pat_obj_dict': 'meta_files/Pat_Obj_DICT.json'
    'num_workers': 8

    'down_HU': -1000
    'up_HU': 1000
    'denom_norm_HU': 500

    'in_size': [96, 128, 144]
    'out_size': [96, 128, 144]

    'norm_oar': True
    'CatStructures': False

    'dose_div_factor': 10 
    
    
model_params:
    num_input_channels: 8
    out_channels: 1
    model_id: 'B'
    kernel_size: 3
    deep_supervision: False
    
lr: 0.0001

num_epochs: 400

act_sig: True

scale_out: 7.5

scale_loss: 4
model_from_lightning: True
#model_from_lightning: False
#save_model_root: ../pretrainmodel/GDP-HMM_Challenge
save_model_root: ../pretrainmodel/GDP-HMM_Challenge/lightning
save_model_path: pretrainmodel/best_model-epoch=356-val_loss=0.2243.ckpt
save_pred_path: 'pretrainmodel/results_val'